config/routes.rb
Rails.application.routes.draw do
  
  root 'watcher#index'
  get 'watcher/index'
  scope '/api' do   
    resources :candidates
    #resources :candidates, only: [:index, :create]
    match '*path', to: 'candidates#index', via: :all
  end
  post '/api/candidates', to: 'candidates#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
    validates :timestamp, presence: true,  uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    start_index = Candidate.count+2
    response = GsheetWatcherService.new(start_index).call

    @gsheet_candidates = (response.values ||[]).map do |gsheet_row|     
      candidate_in_db = Candidate.find_by_timestamp(gsheet_row[0])
      if candidate_in_db
        candidate = candidate_in_db
      else
        candidate = Candidate.new(:timestamp => gsheet_row[0],:first_name => gsheet_row[1],
        :last_name => gsheet_row[2],:email => gsheet_row[3],:phone =>gsheet_row[4],
        :is_syncronized => 0)
      end
      candidate
    end
    render json: { candidates: @gsheet_candidates}
  end

  def create
    @candidate = Candidate.new(candidate_params)
    response = TpApiService.new.call(@candidate)
    @candidate.save
    render json: { body: response.body }, status:response.status
        
  end

  def error
  end
  
  private
  def candidate_params
    params.require(:candidate).permit(:timestamp,:first_name,:last_name,:email,:phone, :is_syncronized)
  end
end

app/controllers/watcher_controller.rb
class WatcherController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/watcher_helper.rb
module WatcherHelper
end

app/views/candidates/create.html.erb
<h1>Creation Page</h1>

app/views/candidates/error.html.erb
<h2>Oops an error ocurred contacting the TalkPush API! Please try again later.</h2> <br/>
<br/>
<%= link_to("<< Back to Candidates", candidatess_path, :class => 'back-link') %>

app/views/candidates/index.html.erb
<div class="candidates index">

    <%= link_to("Refresh", candidates_path, :class => 'action index') %> <br/>

    <table class="listing" summary="Candidate list">
        <tr class="header">
            <% @headers.each do |header| %>
                <th><%= header %></th>
            <% end %>
            <th></th>
        </tr>
        <% @gsheet_candidates.each do |candidate| %>
            <% @candidate = candidate %>
            <%= form_for(@candidate, :url=>{:action=>'create'}) do |f| %>
                <tr>
                <td><%= f.text_field(:timestamp, :readonly => true)  %></td>
                <td><%= f.text_field(:first_name, :readonly => true) %></td>
                <td><%= f.text_field(:last_name, :readonly => true) %></td>
                <td><%= f.text_field(:email, :readonly => true ) %></td>
                <td><%= f.text_field(:phone, :readonly => true ) %></td>
                <td class="center"><%= @candidate.is_syncronized ?  'Syncronized!' :  f.submit("Syncronize") %> </td>           
                </tr>

            <% end %>
        <% end %>
    </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GsheetWatcher</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/watcher/index.html.erb
<%= javascript_pack_tag 'index' %> 